# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/ui/MatchFinishDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_match_finish_dialog(object):
    def setupUi(self, match_finish_dialog):
        match_finish_dialog.setObjectName("match_finish_dialog")
        match_finish_dialog.resize(530, 410)
        match_finish_dialog.setMinimumSize(QtCore.QSize(530, 410))
        match_finish_dialog.setMaximumSize(QtCore.QSize(530, 410))
        self.advance_player_list_label = QtWidgets.QLabel(match_finish_dialog)
        self.advance_player_list_label.setGeometry(QtCore.QRect(340, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.advance_player_list_label.setFont(font)
        self.advance_player_list_label.setAlignment(QtCore.Qt.AlignCenter)
        self.advance_player_list_label.setObjectName("advance_player_list_label")
        self.player_list = QtWidgets.QTableWidget(match_finish_dialog)
        self.player_list.setGeometry(QtCore.QRect(30, 70, 181, 241))
        self.player_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.player_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.player_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.player_list.setObjectName("player_list")
        self.player_list.setColumnCount(2)
        self.player_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.player_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.player_list.setHorizontalHeaderItem(1, item)
        self.player_list.horizontalHeader().setDefaultSectionSize(84)
        self.advance_player_list = QtWidgets.QTableWidget(match_finish_dialog)
        self.advance_player_list.setGeometry(QtCore.QRect(320, 70, 181, 241))
        self.advance_player_list.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.advance_player_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.advance_player_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.advance_player_list.setObjectName("advance_player_list")
        self.advance_player_list.setColumnCount(2)
        self.advance_player_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.advance_player_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.advance_player_list.setHorizontalHeaderItem(1, item)
        self.advance_player_list.horizontalHeader().setDefaultSectionSize(84)
        self.player_list_label = QtWidgets.QLabel(match_finish_dialog)
        self.player_list_label.setGeometry(QtCore.QRect(50, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.player_list_label.setFont(font)
        self.player_list_label.setAlignment(QtCore.Qt.AlignCenter)
        self.player_list_label.setObjectName("player_list_label")
        self.add_btn = QtWidgets.QPushButton(match_finish_dialog)
        self.add_btn.setGeometry(QtCore.QRect(220, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.add_btn.setFont(font)
        self.add_btn.setObjectName("add_btn")
        self.cancel_btn = QtWidgets.QPushButton(match_finish_dialog)
        self.cancel_btn.setGeometry(QtCore.QRect(220, 170, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.cancel_btn.setFont(font)
        self.cancel_btn.setObjectName("cancel_btn")
        self.ok = QtWidgets.QPushButton(match_finish_dialog)
        self.ok.setGeometry(QtCore.QRect(400, 350, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.ok.setFont(font)
        self.ok.setObjectName("ok")
        self.cancel = QtWidgets.QPushButton(match_finish_dialog)
        self.cancel.setGeometry(QtCore.QRect(300, 350, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.cancel.setFont(font)
        self.cancel.setObjectName("cancel")

        self.retranslateUi(match_finish_dialog)
        QtCore.QMetaObject.connectSlotsByName(match_finish_dialog)

    def retranslateUi(self, match_finish_dialog):
        _translate = QtCore.QCoreApplication.translate
        match_finish_dialog.setWindowTitle(_translate("match_finish_dialog", "比賽結算"))
        self.advance_player_list_label.setText(_translate("match_finish_dialog", "晉級選手名單"))
        item = self.player_list.horizontalHeaderItem(0)
        item.setText(_translate("match_finish_dialog", "ID"))
        item = self.player_list.horizontalHeaderItem(1)
        item.setText(_translate("match_finish_dialog", "比賽分數"))
        item = self.advance_player_list.horizontalHeaderItem(0)
        item.setText(_translate("match_finish_dialog", "ID"))
        item = self.advance_player_list.horizontalHeaderItem(1)
        item.setText(_translate("match_finish_dialog", "比賽分數"))
        self.player_list_label.setText(_translate("match_finish_dialog", "比賽選手名單"))
        self.add_btn.setText(_translate("match_finish_dialog", "加入>>"))
        self.cancel_btn.setText(_translate("match_finish_dialog", "<<取消"))
        self.ok.setText(_translate("match_finish_dialog", "確認"))
        self.cancel.setText(_translate("match_finish_dialog", "取消"))


