# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/ui/MatchFinishDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_match_finish_dialog(object):
    def setupUi(self, match_finish_dialog):
        match_finish_dialog.setObjectName("match_finish_dialog")
        match_finish_dialog.resize(670, 480)
        match_finish_dialog.setMinimumSize(QtCore.QSize(670, 480))
        match_finish_dialog.setMaximumSize(QtCore.QSize(670, 480))
        self.advance_player_list_label = QtWidgets.QLabel(match_finish_dialog)
        self.advance_player_list_label.setGeometry(QtCore.QRect(420, 40, 201, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.advance_player_list_label.setFont(font)
        self.advance_player_list_label.setAlignment(QtCore.Qt.AlignCenter)
        self.advance_player_list_label.setObjectName("advance_player_list_label")
        self.player_list = QtWidgets.QTableWidget(match_finish_dialog)
        self.player_list.setGeometry(QtCore.QRect(20, 80, 251, 301))
        self.player_list.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.player_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.player_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.player_list.setObjectName("player_list")
        self.player_list.setColumnCount(3)
        self.player_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.player_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.player_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.player_list.setHorizontalHeaderItem(2, item)
        self.player_list.horizontalHeader().setDefaultSectionSize(120)
        self.advance_player_list = QtWidgets.QTableWidget(match_finish_dialog)
        self.advance_player_list.setGeometry(QtCore.QRect(400, 80, 251, 301))
        self.advance_player_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.advance_player_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.advance_player_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.advance_player_list.setObjectName("advance_player_list")
        self.advance_player_list.setColumnCount(2)
        self.advance_player_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.advance_player_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.advance_player_list.setHorizontalHeaderItem(1, item)
        self.advance_player_list.horizontalHeader().setDefaultSectionSize(120)
        self.player_list_label = QtWidgets.QLabel(match_finish_dialog)
        self.player_list_label.setGeometry(QtCore.QRect(40, 40, 211, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.player_list_label.setFont(font)
        self.player_list_label.setAlignment(QtCore.Qt.AlignCenter)
        self.player_list_label.setObjectName("player_list_label")
        self.add_btn = QtWidgets.QPushButton(match_finish_dialog)
        self.add_btn.setGeometry(QtCore.QRect(290, 140, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.add_btn.setFont(font)
        self.add_btn.setObjectName("add_btn")
        self.remove_btn = QtWidgets.QPushButton(match_finish_dialog)
        self.remove_btn.setGeometry(QtCore.QRect(290, 200, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.remove_btn.setFont(font)
        self.remove_btn.setObjectName("remove_btn")
        self.ok_btn = QtWidgets.QPushButton(match_finish_dialog)
        self.ok_btn.setGeometry(QtCore.QRect(470, 420, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.ok_btn.setFont(font)
        self.ok_btn.setObjectName("ok_btn")
        self.cancel_btn = QtWidgets.QPushButton(match_finish_dialog)
        self.cancel_btn.setGeometry(QtCore.QRect(370, 420, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.cancel_btn.setFont(font)
        self.cancel_btn.setObjectName("cancel_btn")
        self.next_round_label = QtWidgets.QLabel(match_finish_dialog)
        self.next_round_label.setGeometry(QtCore.QRect(100, 420, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.next_round_label.setFont(font)
        self.next_round_label.setObjectName("next_round_label")
        self.next_round = QtWidgets.QComboBox(match_finish_dialog)
        self.next_round.setGeometry(QtCore.QRect(200, 420, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.next_round.setFont(font)
        self.next_round.setMaxCount(6)
        self.next_round.setObjectName("next_round")
        self.next_round.addItem("")
        self.next_round.addItem("")
        self.next_round.addItem("")
        self.next_round.addItem("")
        self.next_round.addItem("")
        self.next_round.addItem("")

        self.retranslateUi(match_finish_dialog)
        self.next_round.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(match_finish_dialog)

    def retranslateUi(self, match_finish_dialog):
        _translate = QtCore.QCoreApplication.translate
        match_finish_dialog.setWindowTitle(_translate("match_finish_dialog", "比賽結算"))
        self.advance_player_list_label.setText(_translate("match_finish_dialog", "晉級選手名單"))
        item = self.player_list.horizontalHeaderItem(0)
        item.setText(_translate("match_finish_dialog", "ID"))
        item = self.player_list.horizontalHeaderItem(1)
        item.setText(_translate("match_finish_dialog", "比賽分數"))
        item = self.player_list.horizontalHeaderItem(2)
        item.setText(_translate("match_finish_dialog", "docId"))
        item = self.advance_player_list.horizontalHeaderItem(0)
        item.setText(_translate("match_finish_dialog", "ID"))
        item = self.advance_player_list.horizontalHeaderItem(1)
        item.setText(_translate("match_finish_dialog", "比賽分數"))
        self.player_list_label.setText(_translate("match_finish_dialog", "比賽選手名單"))
        self.add_btn.setText(_translate("match_finish_dialog", "加入>>"))
        self.remove_btn.setText(_translate("match_finish_dialog", "<<取消"))
        self.ok_btn.setText(_translate("match_finish_dialog", "確認"))
        self.cancel_btn.setText(_translate("match_finish_dialog", "取消"))
        self.next_round_label.setText(_translate("match_finish_dialog", "下一輪:"))
        self.next_round.setItemText(0, _translate("match_finish_dialog", "64強"))
        self.next_round.setItemText(1, _translate("match_finish_dialog", "32強"))
        self.next_round.setItemText(2, _translate("match_finish_dialog", "16強"))
        self.next_round.setItemText(3, _translate("match_finish_dialog", "8強"))
        self.next_round.setItemText(4, _translate("match_finish_dialog", "4強"))
        self.next_round.setItemText(5, _translate("match_finish_dialog", "決賽"))


