# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/mainui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 777)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 777))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 777))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.uncheck_list_label = QtWidgets.QLabel(self.centralwidget)
        self.uncheck_list_label.setGeometry(QtCore.QRect(150, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.uncheck_list_label.setFont(font)
        self.uncheck_list_label.setObjectName("uncheck_list_label")
        self.checked_list_label = QtWidgets.QLabel(self.centralwidget)
        self.checked_list_label.setGeometry(QtCore.QRect(700, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.checked_list_label.setFont(font)
        self.checked_list_label.setObjectName("checked_list_label")
        self.uncheck_list = QtWidgets.QTableWidget(self.centralwidget)
        self.uncheck_list.setGeometry(QtCore.QRect(10, 60, 431, 381))
        self.uncheck_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.uncheck_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.uncheck_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.uncheck_list.setObjectName("uncheck_list")
        self.uncheck_list.setColumnCount(5)
        self.uncheck_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.uncheck_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.uncheck_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.uncheck_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.uncheck_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.uncheck_list.setHorizontalHeaderItem(4, item)
        self.uncheck_list.horizontalHeader().setDefaultSectionSize(84)
        self.checked_list = QtWidgets.QTableWidget(self.centralwidget)
        self.checked_list.setGeometry(QtCore.QRect(560, 60, 431, 701))
        self.checked_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.checked_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.checked_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.checked_list.setObjectName("checked_list")
        self.checked_list.setColumnCount(5)
        self.checked_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.checked_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.checked_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.checked_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.checked_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.checked_list.setHorizontalHeaderItem(4, item)
        self.checked_list.horizontalHeader().setDefaultSectionSize(84)
        self.check_btn = QtWidgets.QPushButton(self.centralwidget)
        self.check_btn.setGeometry(QtCore.QRect(460, 130, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.check_btn.setFont(font)
        self.check_btn.setObjectName("check_btn")
        self.cancel_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_btn.setGeometry(QtCore.QRect(460, 180, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.cancel_btn.setFont(font)
        self.cancel_btn.setObjectName("cancel_btn")
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setGeometry(QtCore.QRect(460, 230, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.delete_btn.setFont(font)
        self.delete_btn.setObjectName("delete_btn")
        self.deleted_list = QtWidgets.QTableWidget(self.centralwidget)
        self.deleted_list.setGeometry(QtCore.QRect(10, 500, 431, 261))
        self.deleted_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.deleted_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.deleted_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.deleted_list.setObjectName("deleted_list")
        self.deleted_list.setColumnCount(5)
        self.deleted_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.deleted_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.deleted_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.deleted_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.deleted_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.deleted_list.setHorizontalHeaderItem(4, item)
        self.deleted_list.horizontalHeader().setDefaultSectionSize(84)
        self.deleted_list_label = QtWidgets.QLabel(self.centralwidget)
        self.deleted_list_label.setGeometry(QtCore.QRect(120, 460, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.deleted_list_label.setFont(font)
        self.deleted_list_label.setObjectName("deleted_list_label")
        self.relife_btn = QtWidgets.QPushButton(self.centralwidget)
        self.relife_btn.setGeometry(QtCore.QRect(460, 660, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.relife_btn.setFont(font)
        self.relife_btn.setObjectName("relife_btn")
        self.refresh_btn = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_btn.setGeometry(QtCore.QRect(460, 590, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.refresh_btn.setFont(font)
        self.refresh_btn.setObjectName("refresh_btn")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "nukl-enroll-client"))
        self.uncheck_list_label.setText(_translate("MainWindow", "未確認清單"))
        self.checked_list_label.setText(_translate("MainWindow", "已確認清單"))
        item = self.uncheck_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "報名時間"))
        item = self.uncheck_list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.uncheck_list.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "項目"))
        item = self.uncheck_list.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "學校"))
        item = self.uncheck_list.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "docID"))
        item = self.checked_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "報名時間"))
        item = self.checked_list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.checked_list.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "項目"))
        item = self.checked_list.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "學校"))
        item = self.checked_list.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "docID"))
        self.check_btn.setText(_translate("MainWindow", "確認>>"))
        self.cancel_btn.setText(_translate("MainWindow", "<<取消"))
        self.delete_btn.setText(_translate("MainWindow", "X刪除X"))
        item = self.deleted_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "報名時間"))
        item = self.deleted_list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.deleted_list.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "項目"))
        item = self.deleted_list.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "學校"))
        item = self.deleted_list.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "docID"))
        self.deleted_list_label.setText(_translate("MainWindow", "已刪除清單"))
        self.relife_btn.setText(_translate("MainWindow", "回復"))
        self.refresh_btn.setText(_translate("MainWindow", "重整"))
